from ratelimit import limits, sleep_and_retry
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO
import time
import os

# Define rate limit parameters
REQUESTS_PER_MINUTE = 20
ONE_MINUTE = 60

@sleep_and_retry
@limits(calls=REQUESTS_PER_MINUTE, period=ONE_MINUTE)
def fetch_webpage(url):
    response = requests.get(url)
    response.raise_for_status()
    return response.text

def convert_toi_to_decimal(toi_str):
    """Convert TOI from 'mm:ss' to decimal minutes."""
    try:
        if isinstance(toi_str, str):
            minutes, seconds = map(int, toi_str.split(':'))
            return minutes + seconds / 60
        return None  # Return None for non-string values
    except ValueError:
        return None

# File paths for the CSV outputs
base_path = r"C:\Users\ashle\Documents\Projects\hockey\data"
leaders_columns = [
    'Player', 'PlayerID', 'Age', 'TeamID', 'Pos', 'GP', 'G', 'A', 'PTS', 'SOG', 'SPCT', 'HIT', 'BLK', 'TOI', 'PIM', 'EVG', 'PPG', 'SHG', 'EVA', 'PPA', 'SHA', 'FOW', 'FOL', 'FO%', 'G_GP', 'A_GP', 'PTS_GP', 'SOG_GP', 'HIT_GP', 'BLK_GP', 'TOI_GP'
]

# Initialize lists to collect data
leaders_data = []

url = 'https://www.hockey-reference.com/leagues/NHL_2025_skaters.html#stats::goals'

try:
    html_content = fetch_webpage(url)
    soup = BeautifulSoup(html_content, 'html.parser')

    table = soup.select_one('#player_stats')
    if table:
        headers = [th.get_text(strip=True) for th in table.select("thead tr")[1].find_all("th")]
        df = pd.read_html(StringIO(str(table)))[0]
        df.columns = headers
        df = df.iloc[:-1, :]
        
        valid_rows = [
            row for row in table.select("tbody tr")
            if not any(cls in (row.get("class") or []) for cls in ["over_header", "thead", "norank"])
            and "League Average" not in row.get_text(strip=True)
        ]

        # Rename columns and clean data
        column_mapping = {'Team': 'TeamID', 'EV': 'EVA', 'PP': 'PPA', 'SH': 'SHA'}
        df.rename(columns=column_mapping, inplace=True)

        df = df[["Player", "Age", "TeamID", "Pos", "GP", "G", "A", "PTS", "SOG", "SPCT", "HIT", "BLK", "TOI", "PIM", "EVG", "PPG", "SHG", "EVA", "PPA", "SHA", "FOW", "FOL", "FO%"]]

        df["TOI"] = df["TOI"].apply(convert_toi_to_decimal)

        # Insert player IDs
        player_ids = [row.select_one("td[data-append-csv]").get("data-append-csv") for row in valid_rows if row.select_one("td[data-append-csv]")]
        df.insert(df.columns.get_loc("Player") + 1, "PlayerID", player_ids + [None] * (len(df) - len(player_ids)))

        # Add per-game stats
        for col in ["G", "A", "PTS", "SOG", "HIT", "BLK", "TOI"]:
            df[f"{col}_GP"] = df[col] / df["GP"]
            df[f"{col}_GP"] = df[f"{col}_GP"].fillna(0)

        df = df.reindex(columns=leaders_columns, fill_value=None)
        leaders_data.append(df)

    time.sleep(3)  # Avoid rate limits

except requests.RequestException as e:
    print(f"Error fetching data: {e}")
except Exception as e:
    print(f"Error processing data: {e}")

# Process leaders_data
if not leaders_data:
    print("No leader data was extracted. Ensure the table exists and the HTML structure is correct.")
else:
    leaders_df = pd.concat(leaders_data, ignore_index=True)
    leaders_df["TeamID"] = leaders_df["TeamID"].replace("UTA", "ARI")
    
    player_info = {
        "acciano01": ("Noel Acciari"),
        "addisca01": ("Calen Addison"),
        "afanaeg01": ("Egor Afanasyev"),
        "ahose01": ("Sebastian Aho"),
        "ahose02": ("Sebastian Aho"),
        "alexani01": ("Nikita Alexandrov"),
        "alexeal01": ("Alexander Alexeyev"),
        "allanno01": ("Nolan Allan"),
        "allenja01": ("Jake Allen"),
        "amadimi01": ("Michael Amadio"),
        "amanni01": ("Nils Aman"),
        "anderfr01": ("Frederik Andersen"),
        "anderja01": ("Jaret Anderson-Dolan"),
        "anderjo05": ("Josh Anderson"),
        "anderjo08": ("Joey Anderson"),
        "andermi02": ("Mikey Anderson"),
        "anderra01": ("Rasmus Andersson"),
        "andraem01": ("Emil Andrae"),
        "anglety01": ("Tyler Angle"),
        "annunju01": ("Justus Annunen"),
        "applema01": ("Mason Appleton"),
        "armiajo01": ("Joel Armia"),
        "arvidvi01": ("Viktor Arvidsson"),
        "astonza01": ("Zach Aston-Reese"),
        "athanan01": ("Andreas Athanasiou"),
        "atkinca01": ("Cam Atkinson"),
        "attarro01": ("Ronnie Attard"),
        "aubekni01": ("Nicolas Aube-Kubel"),
        "audymjo01": ("Jonathan Marchessault"),
        "backlmi01": ("Mikael Backlund"),
        "backos01": ("Oskar Back"),
        "backsni02": ("Nicklas Backstrom"),
        "bahlke01": ("Kevin Bahl"),
        "baileju01": ("Justin Bailey"),
        "bainsar01": ("Arshdeep Bains"),
        "balinuv01": ("Uvis Balinskis"),
        "barabal01": ("Alexander Barabanov"),
        "barbaiv01": ("Ivan Barbashev"),
        "barkoal01": ("Aleksander Barkov"),
        "barreal01": ("Alex Barre-Boulet"),
        "barrity01": ("Tyson Barrie"),
        "barroju01": ("Justin Barron"),
        "barromo01": ("Morgan Barron"),
        "barzama01": ("Mathew Barzal"),
        "bastina01": ("Nathan Bastian"),
        "bathedr01": ("Drake Batherson"),
        "beanja01": ("Jake Bean"),
        "bearet01": ("Ethan Bear"),
        "beauvan01": ("Anthony Beauvillier"),
        "beckmad01": ("Adam Beckman"),
        "bedarco01": ("Connor Bedard"),
        "beechjo01": ("John Beecher"),
        "belpelo01": ("Louis Belpedio"),
        "beniema01": ("Matty Beniers"),
        "bennesa01": ("Sam Bennett"),
        "bennima01": ("Matt Benning"),
        "bennja01": ("Jamie Benn"),
        "benoisi01": ("Simon Benoit"),
        "bensoza01": ("Zach Benson"),
        "berggjo02": ("Jonatan Berggren"),
        "bernaja01": ("Jacob Bernard-Docker"),
        "bertuty01": ("Tyler Bertuzzi"),
        "binnijo01": ("Jordan Binnington"),
        "birobr01": ("Brandon Biro"),
        "bjorkol01": ("Oliver Bjorkstrand"),
        "bjugsni01": ("Nick Bjugstad"),
        "blackco01": ("Colin Blackwell"),
        "blackma01": ("Mackenzie Blackwood"),
        "blakeja02": ("Jackson Blake"),
        "blankni01": ("Nick Blankenburg"),
        "blomqjo01": ("Joel Blomqvist"),
        "bluegte01": ("Teddy Blueger"),
        "blumema01": ("Matej Blumel"),
        "bobrose01": ("Sergei Bobrovsky"),
        "boesebr01": ("Brock Boeser"),
        "bogosza01": ("Zach Bogosian"),
        "boldusa01": ("Samuel Bolduc"),
        "bolduza01": ("Zachary Bolduc"),
        "boldyma01": ("Matt Boldy"),
        "boqviad01": ("Adam Boqvist"),
        "boqvije01": ("Jesper Boqvist"),
        "bordeth01": ("Thomas Bordeleau"),
        "borgewi01": ("Will Borgen"),
        "borturo01": ("Robert Bortuzzo"),
        "bouchev01": ("Evan Bouchard"),
        "bourqma01": ("Mavrik Bourque"),
        "boydtr01": ("Travis Boyd"),
        "branner01": ("Erik Brannstrom"),
        "brattje01": ("Jesper Bratt"),
        "brazeju01": ("Justin Brazeau"),
        "brindga01": ("Gavin Brindley"),
        "brinkbo01": ("Bobby Brink"),
        "brissbr01": ("Brendan Brisson"),
        "brobeph01": ("Philip Broberg"),
        "brodijo01": ("Jonas Brodin"),
        "broditj01": ("Tj Brodie"),
        "brodzjo01": ("Jonny Brodzinski"),
        "brownco02": ("Connor Brown"),
        "brownjo01": ("Josh Brown"),
        "brysoja01": ("Jacob Bryson"),
        "buchnpa01": ("Pavel Buchnevich"),
        "buntimi01": ("Michael Bunting"),
        "burakan01": ("Andre Burakovsky"),
        "burnsbr01": ("Brent Burns"),
        "burroky01": ("Kyle Burroughs"),
        "butleca01": ("Cameron Butler"),
        "byfiequ01": ("Quinton Byfield"),
        "byrambo01": ("Bowen Byram"),
        "caggidr01": ("Drake Caggiula"),
        "carcomi01": ("Michael Carcone"),
        "cardwet01": ("Ethan Cardwell"),
        "carlide01": ("Declan Carlile"),
        "carlobr01": ("Brandon Carlo"),
        "carlsjo01": ("John Carlson"),
        "carlsle01": ("Leo Carlsson"),
        "carrial01": ("Alexandre Carrier"),
        "carrisa01": ("Sam Carrick"),
        "carriwi01": ("William Carrier"),
        "carteje01": ("Jeff Carter"),
        "caseyse01": ("Seamus Casey"),
        "catesno01": ("Noah Cates"),
        "caufico01": ("Cole Caufield"),
        "cecico01": ("Cody Ceci"),
        "celebma01": ("Macklin Celebrini"),
        "cernaer01": ("Erik Cernak"),
        "chaboth01": ("Thomas Chabot"),
        "chaffmi01": ("Mitchell Chaffee"),
        "chartro01": ("Rourke Chartier"),
        "chatfja01": ("Jalen Chatfield"),
        "chiarbe01": ("Ben Chiarot"),
        "chibrni01": ("Nikita Chibrikov"),
        "chinaye01": ("Yegor Chinakhov"),
        "chishde01": ("Declan Chisholm"),
        "cholode01": ("Dennis Cholowski"),
        "chrisja01": ("Jake Christiansen"),
        "chychja01": ("Jakob Chychrun"),
        "chytifi01": ("Filip Chytil"),
        "cirelan01": ("Anthony Cirelli"),
        "cizikca01": ("Casey Cizikas"),
        "claguka01": ("Kale Clague"),
        "clarkbr02": ("Brandt Clarke"),
        "clarkgr01": ("Graeme Clarke"),
        "cliftco01": ("Connor Clifton"),
        "cluttca01": ("Cal Clutterbuck"),
        "coghldy01": ("Dylan Coghlan"),
        "coglian01": ("Andrew Cogliano"),
        "colansa01": ("Sam Colangelo"),
        "coleia01": ("Ian Cole"),
        "colembl01": ("Blake Coleman"),
        "coltoro01": ("Ross Colton"),
        "comphj.01": ("J.T. Compher"),
        "comrier01": ("Eric Comrie"),
        "condolu01": ("Lucas Condotta"),
        "connoky01": ("Kyle Connor"),
        "coolelo01": ("Logan Cooley"),
        "copleph01": ("Pheonix Copley"),
        "coppan01": ("Andrew Copp"),
        "cormilu01": ("Lukas Cormier"),
        "coronma01": ("Matt Coronato"),
        "cottepa01": ("Paul Cotter"),
        "cousini01": ("Nick Cousins"),
        "coutulo01": ("Logan Couture"),
        "coutuse01": ("Sean Couturier"),
        "coylech01": ("Charlie Coyle"),
        "cozendy01": ("Dylan Cozens"),
        "crevilo01": ("Louis Crevier"),
        "crookan01": ("Angus Crookshank"),
        "crosbsi01": ("Sidney Crosby"),
        "crottca01": ("Cameron Crotty"),
        "crousla01": ("Lawson Crouse"),
        "crozima01": ("Maxwell Crozier"),
        "cuyllwi01": ("Will Cuylle"),
        "czarnau01": ("Austin Czarnik"),
        "daccojo01": ("Joey Daccord"),
        "dachki01": ("Kirby Dach"),
        "dadonev01": ("Evgenii Dadonov"),
        "dahlira01": ("Rasmus Dahlin"),
        "danauph01": ("Phillip Danault"),
        "danfoju01": ("Justin Danforth"),
        "deanza01": ("Zach Dean"),
        "debrial01": ("Alex Debrincat"),
        "debruja01": ("Jake Debrusk"),
        "dehaaca01": ("Calvin De Haan"),
        "delbelu01": ("Luca Del Bel Belluz"),
        "delgama01": ("Marc Del Gaizo"),
        "dellaty01": ("Ty Dellandrea"),
        "delmaet01": ("Ethan Del Mastro"),
        "demeldy01": ("Dylan Demelo"),
        "dermotr01": ("Travis Dermott"),
        "deshavi01": ("Vincent Desharnais"),
        "deslani01": ("Nicolas Deslauriers"),
        "desmica01": ("Casey Desmith"),
        "dickija01": ("Jason Dickinson"),
        "digiuph01": ("Phillip Di Giuseppe"),
        "dillobr01": ("Brenden Dillon"),
        "doanjo01": ("Josh Doan"),
        "dobsono01": ("Noah Dobson"),
        "domima01": ("Max Domi"),
        "donatry01": ("Ryan Donato"),
        "dorofpa01": ("Pavel Dorofeyev"),
        "dostalu01": ("Lukas Dostal"),
        "doughdr01": ("Drew Doughty"),
        "dowdni01": ("Nic Dowd"),
        "dowliju01": ("Justin Dowling"),
        "draisle01": ("Leon Draisaitl"),
        "drouijo01": ("Jonathan Drouin"),
        "druryja01": ("Jack Drury"),
        "drysdja01": ("Jamie Drysdale"),
        "dubedi01": ("Dillon Dube"),
        "dubepi01": ("Pierrick Dube"),
        "duboipi01": ("Pierre-Luc Dubois"),
        "duchema01": ("Matt Duchene"),
        "duclaan01": ("Anthony Duclair"),
        "duehrwa01": ("Walker Duehr"),
        "duhaibr01": ("Brandon Duhaime"),
        "dumbama01": ("Matt Dumba"),
        "dumoubr01": ("Brian Dumoulin"),
        "dunnvi02": ("Vince Dunn"),
        "durzise01": ("Sean Durzi"),
        "dvorach01": ("Christian Dvorak"),
        "eberljo01": ("Jordan Eberle"),
        "edmunjo01": ("Joel Edmundson"),
        "edstrad01": ("Adam Edstrom"),
        "edvinsi01": ("Simon Edvinsson"),
        "ehlerni01": ("Nikolaj Ehlers"),
        "eicheja01": ("Jack Eichel"),
        "ekblaaa01": ("Aaron Ekblad"),
        "ekholma01": ("Mattias Ekholm"),
        "eklunwi01": ("William Eklund"),
        "ekmanol01": ("Oliver Ekman-Larsson"),
        "ellerla01": ("Lars Eller"),
        "emberty01": ("Ty Emberson"),
        "engluan01": ("Andreas Englund"),
        "engvapi01": ("Pierre Engvall"),
        "entwima01": ("Mackenzie Entwistle"),
        "eriksjo02": ("Joel Eriksson Ek"),
        "erssosa01": ("Samuel Ersson"),
        "evanglu01": ("Luke Evangelista"),
        "evansja02": ("Jake Evans"),
        "evansry01": ("Ryker Evans"),
        "eyssimi01": ("Michael Eyssimont"),
        "fabbrda01": ("Dante Fabbro"),
        "fabbrro01": ("Robby Fabbri"),
        "faberbr01": ("Brock Faber"),
        "faksara01": ("Radek Faksa"),
        "fantiad01": ("Adam Fantilli"),
        "farabjo01": ("Joel Farabee"),
        "faschhu01": ("Hudson Fasching"),
        "fastje01": ("Jesper Fast"),
        "faulkju01": ("Justin Faulk"),
        "fedotiv01": ("Ivan Fedotov"),
        "feherma01": ("Martin Fehervary"),
        "ferrama01": ("Mario Ferraro"),
        "fialake01": ("Kevin Fiala"),
        "fischch01": ("Christian Fischer"),
        "fixwotr01": ("Trey Fix-Wolansky"),
        "fleurca01": ("Cale Fleury"),
        "fleurha01": ("Haydn Fleury"),
        "fleurma01": ("Marc-Andre Fleury"),
        "foegewa01": ("Warren Foegele"),
        "foersty01": ("Tyson Foerster"),
        "foligma01": ("Marcus Foligno"),
        "foligni01": ("Nick Foligno"),
        "footeno01": ("Nolan Foote"),
        "forbode01": ("Derek Forbort"),
        "forsban01": ("Anton Forsberg"),
        "forsbfi01": ("Filip Forsberg"),
        "forslgu02": ("Gustav Forsling"),
        "foudyje01": ("Jean-Luc Foudy"),
        "foudyli01": ("Liam Foudy"),
        "fowleca01": ("Cam Fowler"),
        "foxad01": ("Adam Fox"),
        "fredetr01": ("Trent Frederic"),
        "froesby01": ("Byron Froese"),
        "frostmo01": ("Morgan Frost"),
        "gadjojo01": ("Jonah Gadjovich"),
        "gallabr01": ("Brendan Gallagher"),
        "gardnrh01": ("Rhett Gardner"),
        "garlaco01": ("Conor Garland"),
        "gaudead01": ("Adam Gaudette"),
        "gaudrfr01": ("Frederick Gaudreau"),
        "gaudrjo01": ("Johnny Gaudreau"),
        "gauncbr01": ("Brendan Gaunce"),
        "gauthcu01": ("Cutter Gauthier"),
        "gauthju01": ("Julien Gauthier"),
        "gavrivl01": ("Vladislav Gavrikov"),
        "gawdigl01": ("Glenn Gawdin"),
        "geekico01": ("Conor Geekie"),
        "geekimo01": ("Morgan Geekie"),
        "georgal01": ("Alexandar Georgiev"),
        "georgis01": ("Isaiah George"),
        "gignabr01": ("Brandon Gignac"),
        "gilbede01": ("Dennis Gilbert"),
        "gilespa01": ("Patrick Giles"),
        "ginniad01": ("Adam Ginning"),
        "giordma01": ("Mark Giordano"),
        "girarsa01": ("Samuel Girard"),
        "girgeze01": ("Zemgus Girgensons"),
        "giroucl01": ("Claude Giroux"),
        "glassco01": ("Cody Glass"),
        "glendlu01": ("Luke Glendening"),
        "goligal01": ("Alex Goligoski"),
        "goncaga01": ("Gage Goncalves"),
        "goodrba01": ("Barclay Goodrow"),
        "gostish01": ("Shayne Gostisbehere"),
        "gourdya01": ("Yanni Gourde"),
        "grafco01": ("Collin Graf"),
        "granlmi01": ("Mikael Granlund"),
        "gravery01": ("Ryan Graves"),
        "greenjo02": ("Jordan Greenway"),
        "greeraj01": ("A.J. Greer"),
        "gregono01": ("Noah Gregor"),
        "greigri01": ("Ridly Greig"),
        "grubaph01": ("Philipp Grubauer"),
        "grudejo02": ("Jonathan Gruden"),
        "grundca01": ("Carl Grundstrom"),
        "grzelma01": ("Matt Grzelcyk"),
        "gudasra01": ("Radko Gudas"),
        "gudbrer01": ("Erik Gudbranson"),
        "guenema01": ("Maxence Guenette"),
        "guentdy01": ("Dylan Guenther"),
        "guentja01": ("Jake Guentzel"),
        "guhleka01": ("Kaiden Guhle"),
        "gushcda01": ("Daniil Gushchin"),
        "gustada01": ("David Gustafsson"),
        "gustaer02": ("Erik Gustafsson"),
        "gustafi01": ("Filip Gustavsson"),
        "guttmco01": ("Cole Guttman"),
        "hagelbr01": ("Brandon Hagel"),
        "hagueni01": ("Nicolas Hague"),
        "hakanja01": ("Jani Hakanpaa"),
        "hallta02": ("Taylor Hall"),
        "halonbr01": ("Brian Halonen"),
        "hamanha01": ("Hardy Haman Aktell"),
        "hamblja01": ("James Hamblin"),
        "hamildo01": ("Dougie Hamilton"),
        "hamontr01": ("Travis Hamonic"),
        "hanifno01": ("Noah Hanifin"),
        "hanlejo01": ("Joel Hanley"),
        "harkija01": ("Jansen Harkins"),
        "harleth01": ("Thomas Harley"),
        "harrijo01": ("Jordan Harris"),
        "hartmry01": ("Ryan Hartman"),
        "harvera01": ("Rafael Harvey-Pinard"),
        "hataksa01": ("Santeri Hatakka"),
        "hathaga01": ("Garnet Hathaway"),
        "haulaer01": ("Erik Haula"),
        "haydejo01": ("John Hayden"),
        "hayeske01": ("Kevin Hayes"),
        "haytoba01": ("Barrett Hayton"),
        "hedmavi01": ("Victor Hedman"),
        "heineda01": ("Danton Heinen"),
        "heineem01": ("Emil Heineman"),
        "heiskmi01": ("Miro Heiskanen"),
        "helleco01": ("Connor Hellebuyck"),
        "henriad01": ("Adam Henrique"),
        "hertlto01": ("Tomas Hertl"),
        "hildede01": ("Dennis Hildeby"),
        "hillad01": ("Adin Hill"),
        "hintzro01": ("Roope Hintz"),
        "hirosak01": ("Akito Hirose"),
        "hischni01": ("Nico Hischier"),
        "hoferjo01": ("Joel Hofer"),
        "hoglani01": ("Nils Hoglander"),
        "hollju01": ("Justin Holl"),
        "hollody01": ("Dylan Holloway"),
        "holmbpo01": ("Pontus Holmberg"),
        "holmssi01": ("Simon Holmstrom"),
        "holtzal01": ("Alexander Holtz"),
        "honzesa01": ("Samuel Honzek"),
        "horvabo01": ("Bo Horvat"),
        "howdebr01": ("Brett Howden"),
        "hronefi01": ("Filip Hronek"),
        "huberjo01": ("Jonathan Huberdeau"),
        "hugheja03": ("Jack Hughes"),
        "hughelu01": ("Luke Hughes"),
        "hughequ01": ("Quinn Hughes"),
        "huntda01": ("Daemon Hunt"),
        "hussovi01": ("Ville Husso"),
        "hutsola01": ("Lane Hutson"),
        "huttobe01": ("Ben Hutton"),
        "huttogr01": ("Grant Hutton"),
        "hymanza01": ("Zach Hyman"),
        "iafalal01": ("Alex Iafallo"),
        "ingraco01": ("Connor Ingram"),
        "ioriovi01": ("Vincent Iorio"),
        "iskharu01": ("Ruslan Iskhakov"),
        "ivaniv01": ("Ivan Ivan"),
        "jankoma01": ("Mark Jankowski"),
        "janmama02": ("Mattias Janmark"),
        "jarnkca01": ("Calle Jarnkrok"),
        "jarrytr01": ("Tristan Jarry"),
        "jarvero01": ("Roby Jarventie"),
        "jarvise01": ("Seth Jarvis"),
        "jeannta01": ("Tanner Jeannot"),
        "jenikja01": ("Jan Jenik"),
        "jennebo01": ("Boone Jenner"),
        "jenseni02": ("Nick Jensen"),
        "jiricda01": ("David Jiricek"),
        "johanal01": ("Albert Johansson"),
        "johanjo03": ("Jonas Johansson"),
        "johanlu01": ("Lucas Johansen"),
        "johanma03": ("Marcus Johansson"),
        "johnser01": ("Erik Johnson"),
        "johnsja02": ("Jack Johnson"),
        "johnske01": ("Kent Johnson"),
        "johnsma04": ("Marc Johnstone"),
        "johnsre01": ("Reese Johnson"),
        "johnsro02": ("Ross Johnston"),
        "johnsry03": ("Ryan Johnson"),
        "johnsty01": ("Tyler Johnson"),
        "johnswy01": ("Wyatt Johnston"),
        "jokihhe01": ("Henri Jokiharju"),
        "jonesca01": ("Caleb Jones"),
        "jonesma03": ("Max Jones"),
        "jonesse01": ("Seth Jones"),
        "jonesza01": ("Zac Jones"),
        "jonssax01": ("Axel Jonsson-Fjallby"),
        "josepma01": ("Mathieu Joseph"),
        "joseppi01": ("Pierre-Olivier Joseph"),
        "joshuda01": ("Dakota Joshua"),
        "josiro01": ("Roman Josi"),
        "juulsno01": ("Noah Juulsen"),
        "kadrina01": ("Nazem Kadri"),
        "kahkoka01": ("Kaapo Kahkonen"),
        "kaisewy01": ("Wyatt Kaiser"),
        "kakkoka01": ("Kaapo Kakko"),
        "kaliyar01": ("Arthur Kaliyev"),
        "kampfda01": ("David Kampf"),
        "kaneev01": ("Evander Kane"),
        "kanepa01": ("Patrick Kane"),
        "kapanka01": ("Kasperi Kapanen"),
        "kapanol01": ("Oliver Kapanen"),
        "kapriki01": ("Kirill Kaprizov"),
        "karlser01": ("Erik Karlsson"),
        "karlsli01": ("Linus Karlsson"),
        "karlswi01": ("William Karlsson"),
        "kartyty01": ("Tye Kartye"),
        "kaspema01": ("Marco Kasper"),
        "kastema01": ("Mark Kastelic"),
        "kelemmi01": ("Milos Kelemen"),
        "kellecl01": ("Clayton Keller"),
        "kellypa01": ("Parker Kelly"),
        "kempead01": ("Adrian Kempe"),
        "kempph01": ("Philip Kemp"),
        "kerfoal01": ("Alex Kerfoot"),
        "kessema01": ("Matthew Kessel"),
        "kessemi01": ("Michael Kesselring"),
        "khusnma01": ("Marat Khusnutdinov"),
        "killoal01": ("Alex Killorn"),
        "kirklju01": ("Justin Kirkland"),
        "kivirjo01": ("Joel Kiviranta"),
        "klapkad01": ("Adam Klapka"),
        "klevety01": ("Tyler Kleven"),
        "kniesma01": ("Matthew Knies"),
        "knighsp01": ("Spencer Knight"),
        "knyzhni01": ("Nikolai Knyzhov"),
        "kochepy01": ("Pyotr Kochetkov"),
        "kochpa01": ("Patrik Koch"),
        "koepkco01": ("Cole Koepke"),
        "koleske01": ("Keegan Kolesar"),
        "kolosal01": ("Aleksei Kolosov"),
        "kolyavl01": ("Vladislav Kolyachonok"),
        "konectr01": ("Travis Konecny"),
        "kopitan01": ("Anze Kopitar"),
        "korchke01": ("Kevin Korchinski"),
        "korczka01": ("Kaedan Korczak"),
        "korpijo01": ("Joonas Korpisalo"),
        "kostikl01": ("Klim Kostin"),
        "kotkaje01": ("Jesperi Kotkaniemi"),
        "kovacjo01": ("Johnathan Kovacevic"),
        "kovalni01": ("Nikolai Kovalenko"),
        "krebspe01": ("Peyton Krebs"),
        "kreidch01": ("Chris Kreider"),
        "krugto01": ("Torey Krug"),
        "kucheni01": ("Nikita Kucherov"),
        "kuempda01": ("Darcy Kuemper"),
        "kulakbr01": ("Brett Kulak"),
        "kulicji01": ("Jiri Kulich"),
        "kulikdm01": ("Dmitry Kulikov"),
        "kuninlu01": ("Luke Kunin"),
        "kuparra01": ("Rasmus Kupari"),
        "kuralse01": ("Sean Kuraly"),
        "kurasph01": ("Philipp Kurashev"),
        "kuzmean01": ("Andrei Kuzmenko"),
        "kuzneya01": ("Yan Kuznetsov"),
        "kylinol01": ("Oliver Kylington"),
        "kyroujo01": ("Jordan Kyrou"),
        "labanke01": ("Kevin Labanc"),
        "labersa01": ("Samuel Laberge"),
        "lacomja01": ("Jackson Lacombe"),
        "laferal01": ("Alex Laferriere"),
        "laffesa01": ("Sam Lafferty"),
        "lafreal01": ("Alexis Lafreniere"),
        "lainepa01": ("Patrik Laine"),
        "lambebr01": ("Brad Lambert"),
        "lamouma01": ("Maveric Lamoureux"),
        "lankike01": ("Kevin Lankinen"),
        "lapiehe01": ("Hendrix Lapierre"),
        "larkidy01": ("Dylan Larkin"),
        "larssad01": ("Adam Larsson"),
        "laughsc01": ("Scott Laughton"),
        "laukoja01": ("Jakub Lauko"),
        "lauzoje01": ("Jeremy Lauzon"),
        "lavoira01": ("Raphael Lavoie"),
        "lazarcu01": ("Curtis Lazar"),
        "leasobr01": ("Brett Leason"),
        "leddyni01": ("Nick Leddy"),
        "leean01": ("Anders Lee"),
        "leean02": ("Andre Lee"),
        "lehkoar01": ("Artturi Lehkonen"),
        "letankr01": ("Kris Letang"),
        "levide01": ("Devon Levi"),
        "lewistr01": ("Trevor Lewis"),
        "lheurza01": ("Zachary L'Heureux"),
        "liljeti01": ("Timothy Liljegren"),
        "lindbos01": ("Oskar Lindblom"),
        "lindees01": ("Esa Lindell"),
        "lindgch01": ("Charlie Lindgren"),
        "lindgry01": ("Ryan Lindgren"),
        "lindhel01": ("Elias Lindholm"),
        "lindhha01": ("Hampus Lindholm"),
        "lindko01": ("Kole Lind"),
        "lizotbl01": ("Blake Lizotte"),
        "lohrema01": ("Mason Lohrei"),
        "lombery01": ("Ryan Lomberg"),
        "lorenst01": ("Steven Lorentz"),
        "lowryad01": ("Adam Lowry"),
        "luchaje01": ("Jett Luchanko"),
        "ludvijo01": ("John Ludvig"),
        "lundean01": ("Anton Lundell"),
        "lundeis01": ("Isac Lundestrom"),
        "lundkni01": ("Nils Lundkvist"),
        "luneatr01": ("Tristan Luneau"),
        "luostee01": ("Eetu Luostarinen"),
        "luukkuk01": ("Ukko-Pekka Luukkonen"),
        "lycksol01": ("Olle Lycksell"),
        "lyonal01": ("Alex Lyon"),
        "lyubuil01": ("Ilya Lyubushkin"),
        "maattol01": ("Olli Maatta"),
        "maccema01": ("Matias Maccelli"),
        "macdeku01": ("Kurtis MacDermid"),
        "maceama01": ("Mackenzie MacEachern"),
        "macewza01": ("Zack MacEwen"),
        "mackina01": ("Nathan MacKinnon"),
        "macleky01": ("Kyle MacLean"),
        "mahurjo01": ("Josh Mahura"),
        "mailllo01": ("Logan Mailloux"),
        "makarca01": ("Cale Makar"),
        "malatja01": ("James Malatesta"),
        "malenbe01": ("Beck Malenstyn"),
        "malinsa01": ("Sam Malinski"),
        "malkiev01": ("Evgeni Malkin"),
        "mancivi01": ("Victor Mancini"),
        "mangian01": ("Andrew Mangiapane"),
        "mansojo01": ("Josh Manson"),
        "manthan01": ("Anthony Mantha"),
        "marchbr03": ("Brad Marchand"),
        "marchki01": ("Kirill Marchenko"),
        "marchma01": ("Mason Marchment"),
        "marinjo01": ("John Marino"),
        "marksja02": ("Jacob Markstrom"),
        "marnemi01": ("Mitch Marner"),
        "maroopa01": ("Pat Maroon"),
        "martial01": ("Alec Martinez"),
        "martiem01": ("Emil Lilleberg"),
        "martijo01": ("Jordan Martinook"),
        "martima02": ("Matt Martin"),
        "mathemi01": ("Mike Matheson"),
        "matinni01": ("Nikolas Matinpalo"),
        "matthau01": ("Auston Matthews"),
        "mayfisc01": ("Scott Mayfield"),
        "mcavoch01": ("Charlie McAvoy"),
        "mcbaija03": ("Jack McBain"),
        "mccabja01": ("Jake McCabe"),
        "mccanja01": ("Jared McCann"),
        "mccarmi01": ("Michael McCarron"),
        "mccorma01": ("Max McCormick"),
        "mcdavco01": ("Connor McDavid"),
        "mcdonry01": ("Ryan McDonagh"),
        "mcginbr01": ("Brock McGinn"),
        "mcginhu01": ("Hugh McGing"),
        "mcgroru01": ("Rutger McGroarty"),
        "mcilrdy01": ("Dylan McIlrath"),
        "mclauma01": ("Marc McLaughlin"),
        "mcleomi01": ("Michael McLeod"),
        "mcleory01": ("Ryan McLeod"),
        "mcmanbo02": ("Bobby McMann"),
        "mcmicco01": ("Connor McMichael"),
        "mcnabbr01": ("Brayden McNabb"),
        "mctavma01": ("Mason McTavish"),
        "mcwarco01": ("Cole McWard"),
        "meierti01": ("Timo Meier"),
        "merceda01": ("Dawson Mercer"),
        "merelwa01": ("Waltteri Merela"),
        "merkuge01": ("Georgii Merkulov"),
        "mermida01": ("Dakota Mermis"),
        "merrijo01": ("Jon Merrill"),
        "merzlel01": ("Elvis Merzlikins"),
        "meyerca01": ("Carson Meyer"),
        "michkma01": ("Matvei Michkov"),
        "middlja01": ("Jake Middleton"),
        "mikheil01": ("Ilya Mikheyev"),
        "mikkoni01": ("Niko Mikkola"),
        "milanso01": ("Sonny Milano"),
        "milleco02": ("Colin Miller"),
        "millejt01": ("J.T. Miller"),
        "milleka01": ("K'Andre Miller"),
        "mintefr01": ("Fraser Minten"),
        "mintypa01": ("Pavel Mintyukov"),
        "miromda01": ("Daniil Miromanov"),
        "mirosiv01": ("Ivan Miroshnichenko"),
        "misyuda01": ("Daniil Misyul"),
        "mitteca01": ("Casey Mittelstadt"),
        "monahse01": ("Sean Monahan"),
        "montesa01": ("Sam Montembeault"),
        "montobr01": ("Brandon Montour"),
        "mooretr01": ("Trevor Moore"),
        "morelma01": ("Mason Morelli"),
        "morrijo04": ("Josh Morrissey"),
        "morrilo01": ("Logan Morrison"),
        "morrosc02": ("Scott Morrow"),
        "moserja01": ("J.J. Moser"),
        "mottety01": ("Tyler Motte"),
        "moverja01": ("Jacob Moverare"),
        "mrazepe01": ("Petr Mrazek"),
        "mukhash01": ("Shakir Mukhamadullin"),
        "murphco02": ("Connor Murphy"),
        "murrabr02": ("Brett Murray"),
        "myersph01": ("Philippe Myers"),
        "myersty01": ("Tyler Myers"),
        "nadeabr01": ("Bradly Nadeau"),
        "namesvl01": ("Vladislav Namestnikov"),
        "nashri02": ("Riley Nash"),
        "nazarfr01": ("Frank Nazar"),
        "necasma01": ("Martin Necas"),
        "nedelal01": ("Alex Nedeljkovic"),
        "neighja01": ("Jake Neighbours"),
        "nelsobr01": ("Brock Nelson"),
        "nemecsi01": ("Simon Nemec"),
        "nesteni02": ("Nikita Nesterenko"),
        "newhoal01": ("Alex Newhook"),
        "nichuva01": ("Valeri Nichushkin"),
        "niedeni01": ("Nino Niederreiter"),
        "nietoma01": ("Matt Nieto"),
        "noesest01": ("Stefan Noesen"),
        "norrijo01": ("Josh Norris"),
        "nosekto01": ("Tomas Nosek"),
        "novakth01": ("Tommy Novak"),
        "nugenry01": ("Ryan Nugent-Hopkins"),
        "nurseda01": ("Darnell Nurse"),
        "nylanwi01": ("William Nylander"),
        "nyquigu01": ("Gustav Nyquist"),
        "obrieli01": ("Liam O'Brien"),
        "oconndr01": ("Drew O'Connor"),
        "oconnlo01": ("Logan O'Connor"),
        "oettija01": ("Jake Oettinger"),
        "ohgreli01": ("Liam Ohgren"),
        "olausos01": ("Oskar Olausson"),
        "oleksja01": ("Jamie Oleksiak"),
        "olivima01": ("Mathieu Olivier"),
        "olofsgu01": ("Gustav Olofsson"),
        "olofsvi01": ("Victor Olofsson"),
        "oreilry01": ("Ryan O'Reilly"),
        "orlovdm01": ("Dmitry Orlov"),
        "oshietj01": ("T.J. Oshie"),
        "ostapza01": ("Zack Ostapchuk"),
        "othmabr01": ("Brennan Othmann"),
        "ovechal01": ("Alex Ovechkin"),
        "pachabr01": ("Brayden Pachal"),
        "pacioma01": ("Max Pacioretty"),
        "pageaje01": ("Jean-Gabriel Pageau"),
        "palaton01": ("Ondrej Palat"),
        "palmiky01": ("Kyle Palmieri"),
        "panarar01": ("Artemi Panarin"),
        "parayco01": ("Colton Parayko"),
        "parssju01": ("Juuso Parssinen"),
        "pastrda01": ("David Pastrnak"),
        "paulni01": ("Nicholas Paul"),
        "paveljo01": ("Joe Pavelski"),
        "pavelon02": ("Ondrej Pavel"),
        "pearsta01": ("Tanner Pearson"),
        "peekean01": ("Andrew Peeke"),
        "pelecad01": ("Adam Pelech"),
        "pelleja01": ("Jakob Pelletier"),
        "perbini01": ("Nick Perbix"),
        "perfeco01": ("Cole Perfetti"),
        "perroda01": ("David Perron"),
        "perryco01": ("Corey Perry"),
        "perunsc01": ("Scott Perunovich"),
        "pescebr01": ("Brett Pesce"),
        "petanni01": ("Nic Petan"),
        "peterjo01": ("Jj Peterka"),
        "petroal01": ("Alexander Petrovic"),
        "petryje01": ("Jeff Petry"),
        "petteel01": ("Elias Pettersson"),
        "pettema01": ("Marcus Pettersson"),
        "pezzemi01": ("Michael Pezzetta"),
        "phillis01": ("Isaak Phillips"),
        "philpno01": ("Noah Philp"),
        "pickaca01": ("Calvin Pickard"),
        "pietral01": ("Alex Pietrangelo"),
        "pintosh01": ("Shane Pinto"),
        "pionkne01": ("Neal Pionk"),
        "podkova01": ("Vasily Podkolzin"),
        "poehlry01": ("Ryan Poehling"),
        "pointbr01": ("Brayden Point"),
        "poitrma01": ("Matthew Poitras"),
        "polinja01": ("Jason Polin"),
        "ponomva01": ("Vasiliy Ponomarev"),
        "pospima01": ("Martin Pospisil"),
        "poturan01": ("Andrew Poturalski"),
        "poulisa01": ("Sam Poulin"),
        "powerow01": ("Owen Power"),
        "primeca01": ("Cayden Primeau"),
        "prishni01": ("Nikita Prishchepov"),
        "protaal01": ("Aliaksei Protas"),
        "provoiv01": ("Ivan Provorov"),
        "puljuje01": ("Jesse Puljujarvi"),
        "pulocry01": ("Ryan Pulock"),
        "puustva01": ("Valtteri Puustinen"),
        "pyyhtmi01": ("Mikael Pyyhtia"),
        "quickjo01": ("Jonathan Quick"),
        "quinnja01": ("Jack Quinn"),
        "raddyda01": ("Darren Raddysh"),
        "raddyta01": ("Taylor Raddysh"),
        "rakelri01": ("Rickard Rakell"),
        "rantami01": ("Mikko Rantanen"),
        "rasmumi01": ("Michael Rasmussen"),
        "ratyaa01": ("Aatu Raty"),
        "ratyak01": ("Aku Raty"),
        "raymolu01": ("Lucas Raymond"),
        "reavery01": ("Ryan Reaves"),
        "regenpa01": ("Pavol Regenda"),
        "reichlu01": ("Lukas Reichel"),
        "reillmi01": ("Mike Reilly"),
        "reimeja01": ("James Reimer"),
        "reinhco01": ("Cole Reinhardt"),
        "reinhsa01": ("Sam Reinhart"),
        "rempash01": ("Sheldon Rempal"),
        "rempema01": ("Matt Rempe"),
        "riellmo01": ("Morgan Rielly"),
        "rifaima01": ("Marshall Rifai"),
        "ristora01": ("Rasmus Ristolainen"),
        "ritchca01": ("Calum Ritchie"),
        "rittida01": ("David Rittich"),
        "roberja01": ("Jason Robertson"),
        "roberni01": ("Nicholas Robertson"),
        "robiner01": ("Eric Robinson"),
        "rodriev01": ("Evan Rodrigues"),
        "romanal01": ("Alexander Romanov"),
        "rondbjo01": ("Jonas Rondbjerg"),
        "rooneke01": ("Kevin Rooney"),
        "roosfi01": ("Filip Roos"),
        "rosenca01": ("Calle Rosen"),
        "rosenis01": ("Isak Rosen"),
        "rosloja01": ("Jack Roslovic"),
        "rossima01": ("Marco Rossi"),
        "rouselu01": ("Lukas Rousek"),
        "royjo01": ("Joshua Roy"),
        "royma04": ("Matt Roy"),
        "royni01": ("Nicolas Roy"),
        "ruhwech01": ("Chad Ruhwedel"),
        "rustbr01": ("Bryan Rust"),
        "ruttaja02": ("Jan Rutta"),
        "ryande01": ("Derek Ryan"),
        "saadbr01": ("Brandon Saad"),
        "sabousc01": ("Scott Sabourin"),
        "sambedy01": ("Dylan Samberg"),
        "samosma01": ("Mackie Samoskevich"),
        "samsoil01": ("Ilya Samsonov"),
        "samuema02": ("Mattias Samuelsson"),
        "sandeja01": ("Jake Sanderson"),
        "sandira01": ("Rasmus Sandin"),
        "sanhetr01": ("Travis Sanheim"),
        "sarosju01": ("Juuse Saros"),
        "savarda01": ("David Savard"),
        "savoima01": ("Matt Savoie"),
        "scandma01": ("Marco Scandella"),
        "scanlbr01": ("Brandon Scanlin"),
        "scheima01": ("Mark Scheifele"),
        "schenbr01": ("Brayden Schenn"),
        "schenlu01": ("Luke Schenn"),
        "schmani01": ("Nick Schmaltz"),
        "schmina01": ("Nate Schmidt"),
        "schnebr01": ("Braden Schneider"),
        "schulju01": ("Justin Schultz"),
        "schwaja01": ("Jaden Schwartz"),
        "schwico01": ("Cole Schwindt"),
        "seeleni01": ("Nick Seeler"),
        "seguity01": ("Tyler Seguin"),
        "seidemo01": ("Moritz Seider"),
        "seneybr01": ("Brett Seney"),
        "sergami01": ("Mikhail Sergachev"),
        "severda01": ("Damon Severson"),
        "sgarbmi01": ("Michael Sgarbossa"),
        "sharaye01": ("Yegor Sharangovich"),
        "shawma01": ("Mason Shaw"),
        "shearco01": ("Conor Sheary"),
        "sheary01": ("Ryan Shea"),
        "sherwki01": ("Kiefer Sherwood"),
        "shestig01": ("Igor Shesterkin"),
        "siegejo01": ("Jonas Siegenthaler"),
        "silfvja01": ("Jakob Silfverberg"),
        "sillico01": ("Cole Sillinger"),
        "silovar01": ("Arturs Silovs"),
        "sissoco01": ("Colton Sissons"),
        "skinnje01": ("Jeff Skinner"),
        "skinnst01": ("Stuart Skinner"),
        "skjeibr01": ("Brady Skjei"),
        "slafkju01": ("Juraj Slafkovsky"),
        "slaggla01": ("Landon Slaggert"),
        "slavija01": ("Jaccob Slavin"),
        "smejkji01": ("Jiri Smejkal"),
        "smithbr05": ("Brendan Smith"),
        "smithco02": ("Cole Smith"),
        "smithcr01": ("Craig Smith"),
        "smithgi01": ("Givani Smith"),
        "smithre01": ("Reilly Smith"),
        "smithwi01": ("Will Smith"),
        "snivejo01": ("Joe Snively"),
        "soderar01": ("Arvid Soderblom"),
        "sodervi01": ("Victor Soderstrom"),
        "sogaama01": ("Mads Sogaard"),
        "solovil01": ("Ilya Solovyov"),
        "sorokil01": ("Ilya Sorokin"),
        "soucyca01": ("Carson Soucy"),
        "sourdju01": ("Justin Sourdif"),
        "spencjo01": ("Jordan Spence"),
        "spronda01": ("Daniel Sprong"),
        "spurgja01": ("Jared Spurgeon"),
        "staaljo01": ("Jordan Staal"),
        "stamkst01": ("Steven Stamkos"),
        "stanklo01": ("Logan Stankoven"),
        "stanllo01": ("Logan Stanley"),
        "stastsp01": ("Spencer Stastney"),
        "stechtr01": ("Troy Stecher"),
        "steelsa01": ("Sam Steel"),
        "steenos01": ("Oskar Steen"),
        "steeval02": ("Alex Steeves"),
        "stenlke01": ("Kevin Stenlund"),
        "stephch02": ("Chandler Stephenson"),
        "stephmi01": ("Mitchell Stephens"),
        "stienma01": ("Matt Stienburg"),
        "stivajo01": ("Jack St. Ivany"),
        "stolaan01": ("Anthony Stolarz"),
        "stonema01": ("Mark Stone"),
        "stromdy01": ("Dylan Strome"),
        "stromry01": ("Ryan Strome"),
        "strubja01": ("Jayden Struble"),
        "stuetti02": ("Tim Stutzle"),
        "sturmni01": ("Nico Sturm"),
        "sundqos01": ("Oskar Sundqvist"),
        "suterpi01": ("Pius Suter"),
        "suterry01": ("Ryan Suter"),
        "suzukni01": ("Nick Suzuki"),
        "svechan01": ("Andrei Svechnikov"),
        "swaymje01": ("Jeremy Swayman"),
        "szubema01": ("Maksymilian Szuber"),
        "talboca01": ("Cam Talbot"),
        "tanevbr01": ("Brandon Tanev"),
        "tanevch01": ("Chris Tanev"),
        "tarasda02": ("Daniil Tarasov"),
        "tarasvl01": ("Vladimir Tarasenko"),
        "tatarto01": ("Tomas Tatar"),
        "tavarjo01": ("John Tavares"),
        "teravte01": ("Teuvo Teravainen"),
        "terrytr01": ("Troy Terry"),
        "texieal01": ("Alexandre Texier"),
        "theodsh01": ("Shea Theodore"),
        "thomaak01": ("Akil Thomas"),
        "thomaro01": ("Robert Thomas"),
        "thompja01": ("Jack Thompson"),
        "thomplo01": ("Logan Thompson"),
        "thompta01": ("Tage Thompson"),
        "thrunhe01": ("Henry Thrun"),
        "timmico01": ("Conor Timmins"),
        "tinorja01": ("Jarred Tinordi"),
        "tippeow01": ("Owen Tippett"),
        "tkachbr01": ("Brady Tkachuk"),
        "tkachma01": ("Matthew Tkachuk"),
        "toewsde01": ("Devon Toews"),
        "toffoty01": ("Tyler Toffoli"),
        "tolvaee01": ("Eeli Tolvanen"),
        "tomasph01": ("Philip Tomasino"),
        "tonindo01": ("Dominic Toninato"),
        "toropal01": ("Alexey Toropchenko"),
        "treniya01": ("Yakov Trenin"),
        "trochvi01": ("Vincent Trocheck"),
        "troubja01": ("Jacob Trouba"),
        "tsyplma01": ("Maxim Tsyplakov"),
        "tuchal01": ("Alex Tuch"),
        "tuckety01": ("Tyler Tucker"),
        "tufteri01": ("Riley Tufte"),
        "turcoal02": ("Alex Turcotte"),
        "tynant.01": ("T.J. Tynan"),
        "ullmali01": ("Linus Ullmark"),
        "vaakaur01": ("Urho Vaakanainen"),
        "valimju01": ("Juuso Valimaki"),
        "vanecvi01": ("Vitek Vanecek"),
        "vanrija01": ("James Van Riemsdyk"),
        "vanritr01": ("Trevor Van Riemsdyk"),
        "varlasi01": ("Semyon Varlamov"),
        "vasilan02": ("Andrei Vasilevskiy"),
        "vatrafr01": ("Frank Vatrano"),
        "vejmeka01": ("Karel Vejmelka"),
        "velenjo01": ("Joe Veleno"),
        "verhaca01": ("Carter Verhaeghe"),
        "veseyji02": ("Jimmy Vesey"),
        "vilarga01": ("Gabriel Vilardi"),
        "vladada01": ("Daniel Vladar"),
        "vlasial01": ("Alex Vlasic"),
        "vlasima01": ("Marc-Edouard Vlasic"),
        "vorondi01": ("Dmitri Voronkov"),
        "vranaja01": ("Jakub Vrana"),
        "wagnech01": ("Chris Wagner"),
        "wahlsol01": ("Oliver Wahlstrom"),
        "walkena01": ("Nathan Walker"),
        "walkesa01": ("Sammy Walker"),
        "walkese01": ("Sean Walker"),
        "walmaja01": ("Jake Walman"),
        "watsoau01": ("Austin Watson"),
        "wedgesc01": ("Scott Wedgewood"),
        "weegama01": ("Mackenzie Weegar"),
        "wennbal01": ("Alex Wennberg"),
        "werenza01": ("Zach Werenski"),
        "whiteza01": ("Zach Whitecloud"),
        "wilsoto01": ("Tom Wilson"),
        "wintery01": ("Ryan Winterton"),
        "wolfdu01": ("Dustin Wolf"),
        "wolljo01": ("Joseph Woll"),
        "woodmi01": ("Miles Wood"),
        "wothepa01": ("Parker Wotherspoon"),
        "wrighsh01": ("Shane Wright"),
        "xhekaar01": ("Arber Xhekaj"),
        "yamamka01": ("Kailer Yamamoto"),
        "yloneje01": ("Jesse Ylonen"),
        "yorkca01": ("Cam York"),
        "zachapa01": ("Pavel Zacha"),
        "zadorni01": ("Nikita Zadorov"),
        "zamulye01": ("Yegor Zamula"),
        "zaryco01": ("Connor Zary"),
        "zegratr01": ("Trevor Zegras"),
        "zellwol01": ("Olen Zellweger"),
        "zettefa01": ("Fabian Zetterlund"),
        "zibanmi01": ("Mika Zibanejad"),
        "zubar01": ("Artem Zub"),
        "zuccama01": ("Mats Zuccarello"),
        "zuckeja01": ("Jason Zucker"),
        "helensa02": ("Samuel Helenius"),
        "jostty01": ("Tyson Jost"),
        "richaan01": ("Anthony Richard"),
        "dewarco01": ("Connor Dewar"),
        "lekkejo01": ("Jonathan Lekkerimaki"),
        "denisgr01": ("Grigori Denisenko"),
        "oestejo01": ("Jordan Oesterle"),
        "helledr01": ("Drew Helleson"),
        "schueco01": ("Corey Schueneman"),
        "pickeow01": ("Owen Pickering"),
        "milnemi01": ("Michael Milne"),
        "brownpa02": ("Patrick Brown"),
        "meyerbe01": ("Ben Meyers"),
        "vielje01": ("Jeffrey Viel"),
        "granshe01": ("Helge Grans"),
        "jonesbe01": ("Ben Jones"),
        "burkeca01": ("Callahan Burke"),
        "haggro01": ("Robert Hagg"),
        "bowersh01": ("Shane Bowers"),
        "shorede01": ("Devin Shore"),
        "grebeni01": ("Nikita Grebenkin"),
        "sassoma01": ("Max Sasson"),
        "svechfe01": ("Fedor Svechkov"),
        "nylanal01": ("Alexander Nylander"),
        "berarbr02": ("Brett Berard"),
        "heinovi01": ("Ville Heinola"),
        "bradlch01": ("Chase Bradley"),
        "wilsbad01": ("Adam Wilsby"),
        "hardmmi01": ("Mike Hardman"),
        "legarna01": ("Nathan Legare")
    }
    
    leaders_df["Player"] = leaders_df["PlayerID"].map(player_info).fillna(leaders_df["Player"])

    # Save to CSV
    leaders_path = os.path.join(base_path, "leaders.csv")
    leaders_df.to_csv(leaders_path, index=False, encoding="utf-8")
    print(f"Leaders saved to {leaders_path}")
    

#goalie_columns = [
#    'Player', 'PlayerID', 'Age', 'TeamID', 'GP', 'GS', 'W', 'L', 'OTL', 'GA', 'SA', 'SV', 'SV%', 'GAA', 'SO'
#]

# Initialize lists to collect data
#goalie_data = []

#url = 'https://www.hockey-reference.com/leagues/NHL_2025_goalies.html#stats::games_goalie'

#try:
#    html_content = fetch_webpage(url)
#    soup = BeautifulSoup(html_content, 'html.parser')

#    table = soup.select_one('#goalie_stats')
#    if table:
#        headers = [th.get_text(strip=True) for th in table.select("thead tr")[1].find_all("th")]
#        df = pd.read_html(StringIO(str(table)))[0]
#        df.columns = headers
#        df = df.iloc[:-1, :]
        
#        valid_rows = [
#            row for row in table.select("tbody tr")
#            if not any(cls in (row.get("class") or []) for cls in ["over_header", "thead", "norank"])
#            and "League Average" not in row.get_text(strip=True)
#        ]

        # Rename columns and clean data
#        column_mapping = {'Team': 'TeamID', 'T/O': 'OTL', 'Shots': 'SA'}
#        df.rename(columns=column_mapping, inplace=True)

#        df = df[['Player', 'Age', 'TeamID', 'GP', 'GS', 'W', 'L', 'OTL', 'GA', 'SA', 'SV', 'SV%', 'GAA', 'SO']]

        # Insert player IDs
#        player_ids = [row.select_one("td[data-append-csv]").get("data-append-csv") for row in valid_rows if row.select_one("td[data-append-csv]")]
#        df.insert(df.columns.get_loc("Player") + 1, "PlayerID", player_ids + [None] * (len(df) - len(player_ids)))

#        df = df.reindex(columns=goalie_columns, fill_value=None)
#        goalie_data.append(df)

#    time.sleep(3)  # Avoid rate limits

#except requests.RequestException as e:
#    print(f"Error fetching data: {e}")
#except Exception as e:
#    print(f"Error processing data: {e}")

#if not goalie_data:
#    print("No goalie data was extracted. Ensure the table exists and the HTML structure is correct.")
#else:
#    goalie_df = pd.concat(goalie_data, ignore_index=True)
#    goalie_df["TeamID"] = goalie_df["TeamID"].replace("UTA", "ARI")
    
#    player_info = {
#        insert players
#        
#    }
    
#    goalie_df["Player"] = goalie_df["PlayerID"].map(player_info).fillna(goalie_df["Player"])

    # Save to CSV
#    goalie_path = os.path.join(base_path, "goalies.csv")
#    goalie_df.to_csv(goalie_path, index=False, encoding="utf-8")
#    print(f"Goalies saved to {goalie_path}")